version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  ghost:
    image: 'bitnami/ghost:latest'
    ports:
      - '49152:2368'
    volumes:
      - 'ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb
    environment:
      - GHOST_HOST=mandomantal
      - GHOST_PORT=49152
      - GHOST_EMAIL=gost@camandmax.us
      - BLOG_TITLE=Cam and Max
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
